### ISSUE TITLE
Authentication UI approaches 

### ISSUE THREAD

**Issue by armantorkzaban** [tcfev/Nextodon-UI-Old#2]
@zabuzara،

در حال حاضر ما در شاخه‌ی main یک interface داریم که شبیه به /nextodon-ui است. ولی هنوز  چند مورد رو برای کارایی کامل نداره:

1. generate mnemonic 
2. هنوز گزینه‌ی signup نشون داده میشه. 

برای این شاخه پیشنهادم اینه:

اونجا که نوشته enter your mnemonic بنویسیم: enter your mnemonic words [or 'generate' new ones]
و generate یه دکمه باشه که کلمات تازه رو میریزه تو text field
4. یه بخش راهنما هم بگذاریم. یعنی یه دکمه‌ی ریزی باشه بالا سمت راست بلوک که چند پاراگراف در مورد BIP39 صحبت کنه و بگه که می‌تونن والت‌های خودشون رو از جای دیگه import کنن، اگر که bip39 هست.

---
در مورد شاخه‌ی testing:

- این شاخه کمی مسیر طولانی‌تری داره ولی همه چیز رو شامل میشه.
- هنوز داره یک مسیر نشون میده /generate. این رو چه طور میشه حذف کرد.
- من بین این دوتا شاخه‌ی main رو ترجیح میدم، چونکه شکل خیلی بی‌دردسری از signup/signin نشون میده و ادعا می‌کنه که این دوتا باهم فرقی ندارن.

**Comment by zabuzara** [comment]
بررسی کردم 
Enter your mnemonic words or (generate new ones)
اوکی هست نوشتنش
اما اگه ر. همین صفحه بزاریم کلید generate که ۱۲ تا کلمه بریزه تو textarea دیگه مراحل verify  نداریم که بدونیم کاربر حتما نوشته این ۱۲ تارو

**Comment by zabuzara** [comment]
یهBranch به اسم SignInUp به این شکل
<img width="472" alt="Screenshot 2023-07-03 at 13 50 18" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/5699650f-76a1-4389-adb9-72ba34295591">
<img width="451" alt="Screenshot 2023-07-03 at 13 50 25" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/fc242cfd-783b-4b18-a1a3-54f4f015cc87">

**Comment by tcf-admin** [comment]
> اما اگه ر. همین صفحه بزاریم کلید generate که ۱۲ تا کلمه بریزه تو textarea دیگه مراحل verify نداریم که بدونیم کاربر حتما نوشته این ۱۲ تارو

بدون وریفای که نمیشه. چه کارش کنیم؟

**Comment by armantorkzaban** [comment]
> اما اگه ر. همین صفحه بزاریم کلید generate که ۱۲ تا کلمه بریزه تو textarea دیگه مراحل verify نداریم که بدونیم کاربر حتما نوشته این ۱۲ تارو

بدون وریفای که نمیشه. چه کارش کنیم؟

**Comment by zabuzara** [comment]
مگر اینکه روی Generate بزنه کاربر بره تو اون صفحه که Passphrase انتخاب میکرد و Tab به Tab جلو میرفت رو switch کنیم و وقتی به گزینه GO TO APP رسید روش زد عملیات login رو احرا کنیم.
Ich werde morgen zeichnen, was ich damit genau meine. Mit Bilder kann man besser die Bestandteile und deren Zusammenhang darstellen. Danach einigen wir uns. @armantorkzaban

**Comment by zabuzara** [comment]
کاربر رو Sign in میزنه وارد این صفحه میشه
<img width="553" alt="Screenshot 2023-07-03 at 23 43 07" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/9b7eaa50-d54b-4d3e-b6ec-182788aea7cb">

 به نظرم Sign up  رو برداریم اسمشو
اگه کاربر رو Generate زد
بره تو این صفحه

<img width="513" alt="Screenshot 2023-07-03 at 23 44 09" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/7b5b6431-1c79-440a-b247-95c6b86d9d05">

از او گزینه Sign in میتونه برگرده همیشه 
Routing در کار نیست 
او یه span element هست

بعد باقی مراحل که صحبت شد به ترتیب

<img width="510" alt="Screenshot 2023-07-03 at 23 44 15" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/ef6d15f2-79de-4dc5-8eb9-f5d929be4f85">

بعد

<img width="530" alt="Screenshot 2023-07-03 at 23 44 23" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/a66f6dad-980b-4626-a6f8-d4ffc4dfc103">


بعد

<img width="479" alt="Screenshot 2023-07-03 at 23 45 27" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/6db35694-6778-460a-9ef1-8967d78b7295">


دقیقا اینحا دیگه اگه کاربر ننوشته باشه mnemonic رو یرگرده از نو 
Genrate صورت میگیره
که از نو کلمات جدیدو وارد میکنه. شاید دردسر ساز باشه مراحل اما کسی که میخاد استفاده کنه عادت میکنه

 اگر ترتیبو درست وارد کرده باشه وارد مرحله بعدی میشه

<img width="488" alt="Screenshot 2023-07-03 at 23 45 38" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/1409b23e-7842-40ac-90af-c2eac0b1e62f">

اینحا با زدن رو GO TO APP عملیات لاگین صورت میگیره
این از همه جیز منطقی تره

**Comment by zabuzara** [comment]
یه راه دیگه هم اینکه اگر رو این صفحه بخوایم بمونیم 
<img width="553" alt="Screenshot 2023-07-03 at 23 43 07" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/dbb201c4-c99b-4db5-9db1-bde19fcd7987">

اما verify هم داشته باشیم اینه که یه popup بیاد بالا بعد از زدن رو Generate که اون ۱۲ کلمه رو نشون بده و به کاربر گوشزد کنیم که بنویس حتما. بعد رو کلید مثلا Written کلید کنه popup بسته شه کلمات بره تو textarea اگر خواست passphrase بعد بزنه رو Sign in ما والت رو از entropy با passphrase بسازیم و عملیات login اعمال شه.

**Comment by zabuzara** [comment]
Wir können auch nachdem die Benutzer auf den Generate Button geklickt haben, auf diesen Übersicht gehen:

<img width="530" alt="Screenshot 2023-07-03 at 23 44 23" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/461d7f78-ac3a-48fb-8150-39d796e99fa4">


Aber dann sollten wir die untere Buttons (Zurück/Weiter) löschen und stattdessen setzen wir eine Taste "Continue with Sign in" oder was ähnliches. Der unterstehende "Already ...." wird auch entfernt. 

Und wenn die Benutzer auf dem "Continue with Sign in" Butten geklickt haben, gehen wir wieder in diese Übersicht 

<img width="553" alt="Screenshot 2023-07-03 at 23 43 07" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/04b9d2b4-bb93-4a9a-9f59-286538ec717b">


Hier werden wir die generierte Mnemonic in den Textarea einfügen und mit bzw. ohne Kennwort Sign In tätigen.

So werden wir ein paar Schritte los.

**Comment by zabuzara** [comment]
@armantorkzaban

**Comment by armantorkzaban** [comment]
Ideen sind super. Ich würde nur anstatt Sign In, Enter Fordem verwenden. Sonst alles sieht gut aus.

**Comment by armantorkzaban** [comment]
Ich würde den kürzeren Weg nehmen.

**Comment by zabuzara** [comment]
<img width="477" alt="Screenshot 2023-07-04 at 15 35 08" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/237b1898-5814-4add-8165-34c77af8307c">

<img width="504" alt="Screenshot 2023-07-04 at 15 35 32" src="https://github.com/tcfev/Nextodon-UI-Old/assets/79631865/54159bf0-fff0-4a66-a4ad-0d79c2a09b01">

@armantorkzaban 


Ich führe morgen Refactoring durch. Und dann die letzte Änderungen und sollte fertig sein.

**Comment by armantorkzaban** [comment]
Super. Übrigens, nach ! brauchen wir keinen Punkt.
