### ISSUE TITLE
Static files to be pushed to Nextodon

### ISSUE THREAD

**Issue by armantorkzaban** [tcfev/Nextodon-UI-Old#4]
@zabuzara 
Könntest du bitte die statischen Verzeichnisse hier hochladen? Die werde ich direct in tcfev/Nextodon (new branch) importieren as PR, es wird getested und gemerged.

**Comment by zabuzara** [comment]
Ist erledigt, ich hab vom Projekt ein Production Build erstellt. Nun ist in einem Branch Namens "PR" vorhanden.

Zum test habe ich auch mit dem Kommando:
```bash
serve -s build
``` 
ausgeführt läuft.

**Comment by armantorkzaban** [comment]
Ich sehe the branch nicht!

**Comment by zabuzara** [comment]
In tcfev/Nextodon

https://github.com/tcfev/nextodon/tree/PR

**Comment by armantorkzaban** [comment]
Oops, nein. Du hast es richtig gemacht. Hatte gedacht, dass das PR in dieser Repo gemacht worden ist. 
Danke!
